version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - intrange
    - misspell
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - usestdlibvars
    - wastedassign
